# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dockerpractice1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://practiceregistryy.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_96648f9da3254e318722049b070acb30 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_fd3bb5dae1444327a5ff0fdbcb92ddca }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: practiceregistryy.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_96648f9da3254e318722049b070acb30 }}/practiceregistryy/practiceregistryy:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dockerpractice1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d35178d7fc404ae89e917ed55cb3c2e3 }}
        images: 'practiceregistryy.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_96648f9da3254e318722049b070acb30 }}/practiceregistryy/practiceregistryy:${{ github.sha }}'