# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dockerpractice1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://practiceregistryy.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_96648f9da3254e318722049b070acb30 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_fd3bb5dae1444327a5ff0fdbcb92ddca }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: practiceregistryy.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_96648f9da3254e318722049b070acb30 }}/practiceregistryy/practiceregistryy:${{ github.sha }}
        file: ./Dockerfile
  script:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        login-server: practiceregistryy.azurecr.io
    
    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          sudo az login --username kartiksalyan7015@gmail.com --password Goku@op69
          sudo az acr login -n practiceregistryy --username practiceregistryy --password KxRDve1stf0tFLWIzIq7FdG08Q4MtwkYuJS+1zcyH6+ACRD0IVRn
          $acrName = "pacticetest"
          $acrRepository = "pacticetest/pacticetest"
          $maxTags = 14
          $tagsCount = (sudo az acr repository show-tags --name $acrName --repository $acrRepository).length-2
          if ($tagsCount -eq $maxTags){ sudo az acr repository show-tags -n $acrName --repository $acrRepository --orderby time_asc --top 1 --query "[0]" --output tsv | foreach { sudo az acr repository delete --name $acrName --image ${acrRepository}:$_ --yes } }
        azPSVersion: "latest"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dockerpractice1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d35178d7fc404ae89e917ed55cb3c2e3 }}
        images: 'practiceregistryy.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_96648f9da3254e318722049b070acb30 }}/practiceregistryy/practiceregistryy:${{ github.sha }}'
