name: running the powershell script

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        login-server: practiceregistryy.azurecr.io
    
    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
         az acr login -n practiceregistryy
        azPSVersion: "latest"
        
